// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("countbeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy0WF1v2zYXvs+vOOjV+wKysCZrMPhiWJYEq7GmDdbk2j0mjyUuEqmSVBzv1w+kqK9Ilp3auwlM8vB5nkOeDyozeKLtHJgqpV0R2jMAK2xG/SlOhmlRWKHk/AxgLSjjxv0CmIHEvDYn7ecA7LagOWRKJmFC0/dSaOJzsLqkMNmFhV/DJMD9p9urr7fweH9z9XALN1+uH+9uPz9cPSy+fD47C4L7Wn8fygx410paFNIAU3mupN8X9AM+o8hwlREICZhlQM8krddu4o6bPT8dQOx+TvvwkJLfAGoNNiWvEAxJLmTiJzKVQE7GYEImhkXHym8TpoEyZJ1At86UXIuk1OjoYC0yity8W0QLz5iVbieUhrjHFNYNpbJdML8FUmVsYAr2D8pT9XREbs1PfXPDbw2O8h7v1hUPD61m3H9wjTY0oMmWWhKH1dZTqYIcjUzAbI2lHJSETSpY2grvnJ0upRQyGVFjRU7/KHmAmtryv1TzTNoIJfeLCYZ1WPlw9pefkHRSiINNhalCOe6H7rvfnCvGYl686+UpR0tTebpWOkfbs6MXzAuXeldlUhoL55c2hfOf3l9G8P58fvFh/uEivrg4P+x0vSTYVIFMIQ1dgmhiSnPYoGn9e+WUxcRMs1zplbAa9dbbVqfF0JUCH+8F6eqiUHI/sBqlQWbb+6jO6RVxVR1656hWfxOrc60aLKuVJ9pulObTQptaVRrSbU65AlWRvVJAWqt+wU20Kotpklu3qa6ArGJ08YucC2eLGQi5Vi6zGRpfvzyPietg6BT/rppQzJr5WpOlF9uZ3CGrlRZw4gEBU3yI3mkxB6E7kCG0wxpA9+/sIPQqTOqemqmStz3q2g2h0OpZcHJuWuRocbxt3YVVWGuVV0jNVuPuqi1ByPnSGyxrSGfJyBild3YxZxr7XXEN+zqxie3J3s+d9tZXGMO9Mka4wPU9yQBqcoARJIwiUBq4SITFTDFCGe/UJqSxKBktxZ7UWQRDWNzUklwTgRxZKuTr1B1j2N+ZGo5uXz+MJRgsO3HWnLM9j3Piosyn2e8qCB9ibyMPzxyRCbtddlpeo6A0M0JjZ+/ZnkLaAQLfEUXb7YSp5AjTtrmJkPO1sbnVRkpYmb0cHnphi9Pyh1JJRlWm7WbXlOxttX95m33+hUTnij35/AmZflOPR8CrNTAWrSu/WUbM9Wyf5tWay1mTKm2XVQeYwxoz4y4NJUuVrvlmTZbveJE3smC0P+yq46EnkI4FP64mPkrxvaQWEAQfq+oNXT7WPt7E2I0LD1e/ToMA95BYlSKzoOSUlE4x+EEl1w2nw5riynBFmRmw9d4SMP2e2KNl4U+i4mmC1gVzG7Ifq9EIyMI9BjqB6rrcoPS0senm90Zm4H5bXB5/Jx/DZ8XwNk4U6VWBGAly1CwVlpgt9Ql86MHB/yhOYnj55XJ5+XMEqPMIioJFkIvC/H8oRZm4yNC6J/1xSr58hRooaGAkrTIRlKtS2jKCjZBcbXaI6H/x/LiGgDPKscZcZNujKSqY4KQmnqKNgNNKoIxgrYlWhk95K4qBhN7UBPsnYawraIv7GXKuyRgyQ4Ic2XFO1jQpar5BTS1ZBKUpMcu2cHd13dVQ15GnckVakiXTVpM/u3MjtO168wzuv2lbUOjWkum22G7aW4B6ouFNZahQ/ATtoXMCheJVbRulKo8tTR2me8XhcXEzJHJ/TYHsdE61iEMy9wV20hN0iDuO8NDmehhRhQY5FkMmlFJZ//+vk9F1IMc5T/lg6fCy3ttlivYET7ZR3gr33wAAAP//DHCbtg=="
}
